def writeUserInput(fileName, getUrl, apiBody, description, expectedResult):
    descriptionWithOutSpace = description.replace(" ", "")
    f = open(fileName, 'a')
    f.write(f"urlOfApi=r'''{getUrl}'''\n\n")
    f.write(f"expectedResultArry={expectedResult}\n\n")
    f.write(f"apiBodyVar=r'''{apiBody}'''\n\n")
    f.write(f"userDefinedDescription=r'{description}'\n\n")
    f.write(f'def {descriptionWithOutSpace}(getUrl, apiBodyVar, description, expectedResult):\n')
    f.write(f"\tpassCount=0\n")
    f.write(f"\tfailCount=0\n\n")
    f.write(f'\tresponse=apiCallFrom(urlOfApi, apiBodyVar)\n\n')
    f.write(f'\tfor expectedResultVal in expectedResultArry:\n')
    f.write(f'\t\tif expectedResultVal in response:\n')
    f.write('\t\t\tprint(f"{expectedResult} is present in response : string match success")\n')
    f.write(f'\t\t\tpassCount+=1\n')
    f.write(f'\t\telse:\n')
    f.write('\t\t\tprint(f"{expectedResult} is not present in response : string match failed")\n')
    f.write(f'\t\t\tfailCount+=1\n')
    f.write('\tprint(f"Pass count : {passCount}")\n')
    f.write('\tprint(f"Fail count : {failCount}")\n\n')
    f.write(f'\tif failCount > 0:\n')
    f.write('\t\tprint(f"{userDefinedDescription} : FAIL")\n')
    f.write(f'\t\treturn passCount, failCount\n')
    f.write(f'\telse:\n')
    f.write('\t\tprint(f"{userDefinedDescription} : PASS")\n')
    f.write(f'\t\treturn passCount, failCount\n\n\n')
    f.write(f'{descriptionWithOutSpace}={descriptionWithOutSpace}(urlOfApi, apiBodyVar, userDefinedDescription, expectedResultArry)\n\n')
    f.write(f'TotalPass+={descriptionWithOutSpace}[0]\n')
    f.write(f'TotalFail+={descriptionWithOutSpace}[1]\n\n\n\n')
    f.close()
    