def writeUserInput(fileName, getUrl, variableName, apiBody, description, expectedResult, incrementalValue):
    f = open(fileName, 'a')
    f.write(f"urlOfApi{incrementalValue}=r'''{getUrl}'''\n\n")
    f.write(f"expectedResultArry{incrementalValue}={expectedResult}\n\n")
    f.write(f"{variableName}=r'''{apiBody}'''\n\n")
    f.write(f"userDefinedDescription=r'{description}'\n\n")
    f.write(f"passCount=0\n")
    f.write(f"failCount=0\n\n")
    f.write(f'response{incrementalValue}=apiCallFrom(urlOfApi{incrementalValue}, {variableName})\n\n')
    f.write(f'for expectedResult in expectedResultArry{incrementalValue}:\n')
    f.write(f'\tif expectedResult in response{incrementalValue}:\n')
    f.write('\t\tprint(f"{expectedResult} is present in response : string match success")\n')
    f.write(f'\t\tpassCount+=1\n')
    f.write(f'\telse:\n')
    f.write('\t\tprint(f"{expectedResult} is not present in response : string match failed")\n')
    f.write(f'\t\tfailCount+=1\n')
    f.write('print(f"Total num of pass count : {passCount}")\n')
    f.write('print(f"Total num of fail count : {failCount}")\n\n')
    f.write(f'if failCount > 0:\n')
    f.write('\tprint(f"{userDefinedDescription} : FAIL")\n')
    f.write(f'else:\n')
    f.write('\tprint(f"{userDefinedDescription} : PASS")\n\n\n\n')
    